Bienvenue sur Trendhub-Affiliates
clien 1 et 2
Lebonboin
<li><a href="votre-lien-affiliation-produit-1" target="_blank">Produit 1</a></li>
        <li><a href="votre-lien-affiliation-produit-2" target="_blank">Produit 2</a></li>
        <!-- Ajoutez d'autres produits selon vos besoins -->
    </ul>
    <p>En cliquant sur les liens et en effectuant un achat, vous soutenez ce site. Merci pour votre soutien !</p>
    <footer>
        <p>&copy; 2023 fatima Lebonboin. Tous droits réservés.</p>
    </footer>
</body>
</html>
